project:
  type: website

website:
  title: "Cali A. Wilson"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - projects.qmd
      - about.qmd


format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

